spring:
  main:
    log-startup-info: true
  datasource:
    url: jdbc:postgresql://database-1.c3m0mywwuswl.us-east-2.rds.amazonaws.com:5432/zafin
    #url: jdbc:postgresql://localhost:5432/zafin
    username: dm
    password: dm
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        generate_statistics: false      
        dialect: org.hibernate.dialect.PostgreSQLDialect      
        format_sql: true  # Makes the SQL readable with line breaks    
aws:
  region: us-east-2
  s3:
    bucket-name: demo-stock-ranking-bucket-2026
finnhub:
  api:
    key: d8qrd6pr01quatd8ohu0d8qrd6pr01quatd8ohug      
    url: https://finnhub.io/api/v1/quote    
management:
  endpoints:
    web:
      exposure:
        include: startup    
debug: false    
logging:
  file:
    path: /home/ec2-user/log    