spring:
  datasource:
    url: jdbc:postgresql://database-1.c3m0mywwuswl.us-east-2.rds.amazonaws.com:5432/zafin
    #url: jdbc:postgresql://localhost:5432/zafin
    username: dm
    password: dm
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect      
        format_sql: true  # Makes the SQL readable with line breaks    
aws:
  region: us-east-2
  s3:
    bucket-name: demo-stock-ranking-bucket-2026